name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: shubham1361/wisecow-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

    - name: Install kubectl
      run: |
        # curl -LO https://dl.k8s.io/release/v1.27.3/bin/linux/amd64/kubectl
        # chmod +x ./kubectl
        # sudo mv ./kubectl /usr/local/bin/kubectl
        
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Start Minikube
      run: |
         minikube start --driver=docker --force
         minikube update-context
         minikube kubectl -- get pods

    - name: Check Minikube status and config
      run: |
        minikube status
        kubectl config view
        kubectl cluster-info
        
    - name: Set up Kubernetes configuration
      run: |
        mkdir -p $HOME/.minikube
        sudo cp -r /root/.minikube/* $HOME/.minikube/
        sudo chown -R $(id -u):$(id -g) $HOME/.minikube
        mkdir -p $HOME/.kube
        sudo cp -r /root/.kube/* $HOME/.kube/
        sudo chown -R $(id -u):$(id -g) $HOME/.kube
          


      
        # sudo cp /root/.minikube/profiles/minikube/client.crt $HOME/.kube/
        # sudo cp /root/.minikube/profiles/minikube/client.key $HOME/.kube/
        # sudo cp /root/.minikube/ca.crt $HOME/.kube/
        # sudo chown -R $(id -u):$(id -g) $HOME/.kube
        # ls -la $HOME/.kube
        

    - name: Deploy to Kubernetes
      run: |
         kubectl apply -f deployment.yaml
    #     kubectl apply -f service.yaml
